CREATE TABLE IF NOT EXISTS anime (
	mal_id INTEGER NOT NULL UNIQUE,
	url TEXT NOT NULL,
	image_jpg TEXT,
	image_webp TEXT,
	title TEXT NOT NULL,
	title_english	TEXT,
	title_japanese TEXT,
	title_synonyms TEXT,
	type TEXT,
	source TEXT,
	episodes INTEGER,
	status TEXT,
	aired_from TIMESTAMP,
	aired_to TIMESTAMP,
	rating TEXT,
	score NUMERIC,
	scored_by INTEGER,
	rank INTEGER,
	popularity INTEGER,
	members INTEGER,
	favorites INTEGER,
	season TEXT,
	year INTEGER,
	broadcast_day TEXT,
	broadcast_time TIME,
	PRIMARY KEY(mal_id)
);
CREATE TABLE IF NOT EXISTS demographic (
	dem_id INTEGER NOT NULL,
	mal_id INTEGER NOT NULL,
	name TEXT NOT NULL,
	FOREIGN KEY(mal_id) REFERENCES anime(mal_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS genre (
	gen_id INTEGER NOT NULL,
	mal_id INTEGER NOT NULL,
	name TEXT NOT NULL,
	FOREIGN KEY(mal_id) REFERENCES anime(mal_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS licensor (
	lic_id INTEGER NOT NULL,
	mal_id INTEGER NOT NULL,
	name TEXT NOT NULL,
	FOREIGN KEY(mal_id) REFERENCES anime(mal_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS producer (
	prod_id INTEGER NOT NULL,
	mal_id INTEGER NOT NULL,
	name TEXT NOT NULL,
	FOREIGN KEY(mal_id) REFERENCES anime(mal_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS studio (
	stud_id INTEGER NOT NULL,
	mal_id INTEGER NOT NULL,
	name TEXT NOT NULL,
	FOREIGN KEY(mal_id) REFERENCES anime(mal_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS theme (
	theme_id INTEGER NOT NULL,
	mal_id INTEGER NOT NULL,
	name TEXT NOT NULL,
	FOREIGN KEY(mal_id) REFERENCES anime(mal_id) ON DELETE CASCADE ON UPDATE CASCADE
);